name: web-img-optimizer CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn install --frozen-lockfile
      - run: yarn test
  build-tarballs:
    runs-on: ubuntu-latest
    name: Build tarballs
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          path: dist/
  build-installers:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: deb
          - os: macos-latest
            platform: macos
          - os: windows-latest
            platform: win
    name: Build installer for ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn install --frozen-lockfile
      - name: Build Linux or MacOS installer
        if: ${{ matrix.platform == 'deb' || matrix.platform == 'macos' }}
        run: yarn build:${{ matrix.platform }}
      - name: Build Windows installer
        if: ${{ matrix.platform == 'win' }}
        run: yarn build:win
      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          path: dist/
