name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn install --frozen-lockfile
      - run: yarn test
  build-tarballs:
    runs-on: ubuntu-latest
    name: Build tarballs
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          path: dist/
  build-installers:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - platform: macos
            os: macos-latest
          - platform: win
            os: ubuntu-latest
          - platform: deb
            os: ubuntu-latest
    name: Build installer for ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn install --frozen-lockfile
      - name: Install building tools for Windows
        if: ${{ matrix.platform == 'win' }}
        run: |
          sudo apt-get update
          sudo apt-get install nsis p7zip-full
      - name: Build installer
        run: sudo yarn build:${{ matrix.platform }}
      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          path: dist/
